export const ALLOWED_BLOCKS = [
  'core/paragraph',
  'cpc/heading-one',
  'cpc/heading-two',
  'cpc/heading-three',
  'cpc/heading-four',
  'cpc/heading-five',
  'cpc/heading-six',
  'cpc/quote',
  'core/columns',
  'cpc/link-button',
  'cpc/split-panel',
  'cpc/wrapper',
  'cpc/drawer-list',
  'cpc/drawer',
  'cpc/upcoming-events',
];
